# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-26 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axfday', '0003_mainshow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainshow',
            table='axf_mainshow',
        ),
    ]
