# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-26 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axfday', '0004_auto_20180826_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'axf_goods',
            },
        ),
    ]
