# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-26 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axfday', '0009_goods_goodstypes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='GoodsTypes',
        ),
    ]
