# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-27 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axfday', '0016_auto_20180827_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='current_num',
            field=models.IntegerField(default=0, verbose_name='当前显示数量'),
        ),
    ]
