# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-16 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='公司名字')),
            ],
        ),
        migrations.CreateModel(
            name='MyAs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='空姐名字')),
                ('face_score', models.IntegerField(verbose_name='颜值')),
                ('ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t04.AirCompany', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '空姐',
            },
        ),
    ]
